using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CastleDBGen
{
    internal class LuaWriter : BaseDBWriter
    {
        static readonly string LuaClassStart = "{0} = {{ }}"; // class SHEETNAME
        static readonly string LuaClassEnd = "};\n";
        static readonly string LuaProperty = "{0} {1};\n"; // Type name;\n

        public override void WriteClassDefinitions(CastleDB database, string fileBase, string sourceFileName, Dictionary<string, string> switches, List<string> errors)
        {
            int tabDepth = 0;
            string fileText = string.Format("-- AUTOGENERATED LUA SOURCE CODE FROM {0}\r\n", sourceFileName);

            bool integerIDs = false;
            if (switches.ContainsKey("id"))
                integerIDs = switches["id"].Equals("int");

            bool binIO = false;
            bool jsonOff = false;
            if (switches.ContainsKey("bin"))
            {
                binIO = switches["bin"].Equals("on") || switches["bin"].Equals("only");
                jsonOff = switches["bin"].Equals("only");
            }

            foreach (CastleSheet sheet in database.Sheets)
            {
                string sheetName = sheet.Name.Replace("@","_");
                fileText += string.Format("\r\nfunction ResolveReferences{0}(self, database)\r\n", sheetName);

                foreach (CastleColumn col in sheet.Columns)
                {
                    if (col.TypeID == CastleType.Ref)
                        fileText += string.Format("{0}self.{1} = database:FindTable(\"{2}\", self.{1}Key, \"{3}\")\r\n", GetTabstring(0), col.Name, col.Key, database.Sheets.FirstOrDefault(s => s.Name.Equals(col.Key)).IDColumn.Name);
                }

                if (!jsonOff)
                    fileText += string.Format("\r\nfunction Load{0}(self, jobject)\r\n", sheetName);
                string binLoadText = string.Format("\r\nfunction Load{0}Binary(self, source)\r\n", sheetName);
                string binWriteText = string.Format("\r\nfunction Save{0}(self, dest)\r\n", sheetName);

                foreach (CastleColumn col in sheet.Columns)
                {
                    switch (col.TypeID)
                    {
                    case CastleType.UniqueIdentifier:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1} = value[\"{1}\"]:Getstring()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1} = source:Readstring()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:Writestring(self.{1});\r\n", GetTabstring(tabDepth + 0), col.Name);
                        break;
                    case CastleType.Boolean:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1} = value[\"{1}\"]:GetBool()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1} = source:ReadBool()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:WriteBool(self.{1});\r\n", GetTabstring(tabDepth + 0), col.Name);
                        break;
                    case CastleType.Color:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1}.FromUInt(value[\"{1}\"]:GetUInt())\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1} = source:ReadColor()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:WriteColor(self.{1});\r\n", GetTabstring(tabDepth + 0), col.Name);
                        break;
                    case CastleType.Enum:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1} = value[\"{1}\"]:GetInt()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1} = source:ReadInt()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:WriteInt(self.{1});\r\n", GetTabstring(tabDepth + 0), col.Name);
                        break;
                    case CastleType.File:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1} = value[\"{1}\"]:Getstring()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1} = source:Readstring()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:Writestring(self.{1});\r\n", GetTabstring(tabDepth + 0), col.Name);
                        break;
                    case CastleType.Flags:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1} = value[\"{1}\"]:GetUInt()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1} = source:ReadUInt()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:WriteUInt(self.{1});\r\n", GetTabstring(tabDepth + 0), col.Name);
                        break;
                    case CastleType.Float:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1} = value[\"{1}\"]:GetFloat()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1} = source:ReadFloat()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:WriteFloat(self.{1});\r\n", GetTabstring(tabDepth + 0), col.Name);
                        break;
                    case CastleType.Integer:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1} = value[\"{1}\"]:GetInt()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1} = source:ReadInt()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:WriteInt(self.{1});\r\n", GetTabstring(tabDepth + 0), col.Name);
                        break;
                    case CastleType.List:
                        if (!jsonOff)
                        {
                            fileText += string.Format("{0}local {1}Array = value[\"{1}\"]\r\n", GetTabstring(tabDepth + 0), col.Name);
                            fileText += string.Format("{0}for i = 0, {1}Array:Size() do\r\n", GetTabstring(tabDepth + 0), col.Name);
                            fileText += string.Format("{0}local val = {{ }}\r\n", GetTabstring(tabDepth + 1), string.Format("{0}_{1}", sheetName, col.Name));
                            fileText += string.Format("{0}Load{1}(val, {1}Array[i])\r\n{0}{2}[#{2}+1] = val\r\n", GetTabstring(tabDepth + 1), col.Name, col.Name);
                            binLoadText += string.Format("{0}end\r\n", GetTabstring(tabDepth + 0));
                        }

                        binLoadText += string.Format("{0}local {1}Ct = source:ReadUInt()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}for i = 0, {1}Ct - 1 do\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}local val = {{ }}\r\n", GetTabstring(tabDepth + 1), string.Format("{0}_{1}", sheetName, col.Name));
                        binLoadText += string.Format("{0}Load{1}(val, source)\r\n{0}{2}[#{2}+1], val)\r\n", GetTabstring(tabDepth + 1), col.Name, col.Name);
                        binLoadText += string.Format("{0}end\r\n", GetTabstring(tabDepth + 0));

                        binWriteText += string.Format("{0}dest:WriteUInt(table.getn(self.{1}))\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}for i = 0, table.getn(self.{1}) - 1 do\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}self.{1}[i]:Save{2}(source)\t\n", GetTabstring(tabDepth + 1), col.Name, col.Key);
                        binWriteText += string.Format("{0}end\r\n", GetTabstring(tabDepth + 0));

                        break;
                    case CastleType.Ref:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1}Key = value[\"{1}\"]:Getstring()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1}Key = source:Readstring()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:Writestring({1}.{2})\r\n", GetTabstring(tabDepth + 0), col.Name, database.Sheets.FirstOrDefault(s => s.Name.Equals(col.Key)).IDColumn.Name);
                        break;
                    case CastleType.Text:
                        if (!jsonOff)
                            fileText += string.Format("{0}self.{1} = value[\"{1}\"]:Getstring()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binLoadText += string.Format("{0}self.{1} = source:Readstring()\r\n", GetTabstring(tabDepth + 0), col.Name);
                        binWriteText += string.Format("{0}dest:Writestring(self.{1})\r\n", GetTabstring(tabDepth + 0), col.Name);
                        break;
                    }
                }

                fileText += string.Format("{0}self.ResolveReferences = ResolveReference{1}\r\n", GetTabstring(tabDepth + 0), sheetName);
                binLoadText += string.Format("{0}self.ResolveReferences = ResolveReference{1}\r\n", GetTabstring(tabDepth + 0), sheetName);
                fileText += "end\r\n";
                binLoadText += "end\r\n";
                binWriteText += "end\r\n";

                if (binIO)
                {
                    fileText += binLoadText;
                    fileText += binWriteText;
                }
            }

            fileText +=
"\r\nfunction FindDatabaseTable(self, recordValue, tableName, recordName)\r\n" +
"    for k, v in ipairs(self) do\r\n" +
"        if k == tableName then\r\n" +
"            if v[tableName][recordName] == recordValue then\r\n" +
"                return v[tableName]\r\n" +
"            end\r\n" +
"        end\r\n" +
"    end\r\n" +
"end\r\n";

            fileText += "\r\nfunction LoadDatabase(file)\r\n" +
"    local db = { }\r\n" +
"    -- load the data from file\r\n" +
"    for k = 0, file:GetRoot():Size() do\r\n" +
"        local sheet = file:GetRoot()[k]\r\n" +
"        local sheetName = sheet:Get(\"name\"):Getstring()\r\n";

            foreach (CastleSheet sheet in database.Sheets)
            {
                string sheetName = sheet.Name.Replace("@", "_");
                fileText += string.Format("        if sheetName == \"{0}\" then\r\n", sheetName) +
                                          "            local linesElem = sheet:Get(\"lines\")\r\n" +
                                          "            for ln = 0, linesElem:Size() do\r\n" +
                                          "                local val = { }\r\n";
                fileText += string.Format("                Load{0}(linesElem[ln])\r\n", sheetName);
                fileText += string.Format("                db.{0}List[#db.{0}List + 1] = val\r\n", sheetName);
                fileText +=               "            end\r\n";
                fileText +=               "        end\r\n";
            }

            fileText += "    end\r\n";
            fileText += "    for k,v in ipairs(db) do\r\n";
            fileText += "        for kk, vv in ipairs(v) do\r\n";
            fileText += "            vv:ResolveReferences()\r\n";
            fileText += "        end\r\n";
            fileText += "    end\r\n";
            fileText += "end\r\n";

            System.IO.File.WriteAllText(fileBase, fileText);
        }
    }
}
